---
- name: conveying files via template
  template:
    src: "{{item.src_file}}"
    dest: "{{item.dest_file}}"
  loop:
    - {
        src_file: "nginx.conf.j2",
        dest_file: "/etc/nginx/nginx.conf",
      }
    - {
      src_file: "fastcgi_params.j2",
      dest_file: "/etc/nginx/fastcgi_params",
    }
  notify:
    - reload_nginx

- name: remove simlink default
  file:
    path: "/etc/nginx/sites-enabled/default"
    state: absent
  notify:
    - reload_nginx
